### ISSUE TITLE
Make decorators less verbose

### ISSUE THREAD

**Issue by playerx** [indigotech/graphql-schema-decorator#12]
Hi guys, at first I want to say Great Work! You have big improvements after graphql-decorator and I've some ideas how to make this library more flexible:

Main idea is to have as few decorators as possible:

```
before:
    @NonNull()
    @Pagination()
    @Field({type: UserType})
```

```
after:
    @Field({type: UserType, notNull: true, pagination: true})
```
<hr>

```
before:
    @ObjectType()
    @Description('An user')
```

```
after:
    @ObjectType({description: 'An user'})
```

What do you think?

**Comment by felipesabino** [comment]
@playerx 

Thanks for the feedback! 

I definitely agree that the decorators are very verbose as they are now, and using objects as parameters like you are suggesting will make it the code using it a lot more readable.

The only thing blocking us to move in that direction is that the way the code handles the metadata makes it a little tricky to do these modifications in a simple manner.

But anyway, if you would like to start implementing it before we do please fell free to send us a PR, even if it is as a implementation suggestion 😉

**Comment by playerx** [comment]
I think I know how to make it possible, just give me some time and I'll send pull request about that
