### ISSUE TITLE
Normalize formatting

### ISSUE THREAD

**Issue by felipesabino** [indigotech/graphql-schema-decorator#20]
- Add `.editorconfig` to root folder
- Normalize spacing to tab/spaces and whatever value, as long it is the same for all project.

**Comment by askmon** [comment]
One thing that can help is adding the number of spaces to [tslint](https://github.com/indigotech/graphql-schema-decorator/blob/master/tslint.json#L66) file: https://palantir.github.io/tslint/rules/indent/

This way you will find the ones that are wrong more easily and will also have a fallback for editorconfig
