### ISSUE TITLE
Refactor decorators class structure

### ISSUE THREAD

**Issue by felipesabino** [indigotech/graphql-schema-decorator#22]
- [x] Refactor decorators to use new folder structure
```
- decorator
- metadata-builder
- metadata
  - args
  - types
  - options
- type-factory
- specs
```
- [x] Avoid using `Reflect.defineMetadata` and `Reflect.getMetadata` all over the code base to improve readability. Use specific `MetadataArgsStorage` methods instead.
- Deprecate support decorators due to improvement from #14 
  - [x] `@Pagination`
  - [x] `@Description`
  - [x] `@List`
  - [x] `@NonNull`
  - [x] `@UseContainer` - Remove decorator and add it as a function like [useContainer](https://github.com/pleerock/routing-controllers#using-di-container) from [pleerock/routing-controller](https://github.com/pleerock/routing-controllers)

- Decorators
  - [x] `@UnionType`
  - [x] `@EnumType` + `@Value`
  - [x] `@Field` + `@Arg` + `@OrderBy` + `@Root` + `@Before` + `@Ctx`
  - [x] `@ObjectType`
  - [x] `@InputObjectType`
  - [x] `@Query`
  - [x] `@Mutation`
  - [x] `@Subscription`
  - [x] `@Schema`

**Comment by thiago-soliveira** [comment]
Just some info about the `@UseContainer()` decorator. Its role is to tell the graphql decorator to use the passed container for classes instatiation, just so the `typedi` injection works on classes decorated with `ObjectType` or `InputObjectType`. 
So... It was implemented as a decorator, but it actually should be a function that would get called on app configuration. Just like [useContiner](https://github.com/pleerock/routing-controllers#using-di-container) from [pleerock/routing-controller](https://github.com/pleerock/routing-controllers)

**Comment by felipesabino** [comment]
> So... It was implemented as a decorator, but it actually should be a function that would get called on app configuration

Oh sure! I completely missed that on #32 (https://github.com/indigotech/graphql-schema-decorator/pull/32/files#diff-b4975713b292137c31ec2d18544e2323). I updated the issue description to reflect your comment, thanks! 👍
