### ISSUE TITLE
Create Interface Decorator

### ISSUE THREAD

**Issue by felipesabino** [indigotech/graphql-schema-decorator#28]
Add GraphQL Interfaces to the schema

Reference: http://graphql.org/learn/schema/#interfaces

**Comment by felipesabino** [comment]
This might help reuse code to avoid duplicating classes for both input and output object types.

An example implementation of the decorators might be

```
@InterfaceType()
export class MyInterface {
     @Field()
     interfaceField: string;
}

@ObjectType({interface: MyInterface)
export MyObjectClass {
     @Field()
     objectField: string;
}

@InputObjectType({interface: MyInterface)
export MyInputClass {
     @Field()
     inputField: string;
}

```

And the generated schema should be

```
interface MyInterface {
  interfaceField: String
}

type MyObjectClass implements MyInterface {
  interfaceField: String
  objectField: String
}

input MyInputClass implements MyInterface {
  interfaceField: String
  inputField: String
}

```

### A few caveats

- I didn't test the schema to make sure it is valid, as far as graphql docs goes there isn't a specific disclaimer regarding interfaces and input types, so I am assuming that anything goes.
- Actual typescript interfaces can not have decorators, so a class must be used to accomplish the desired schema,
- The decorators are for schema only, it does not care about you actual code classes/interfaces, so to be consistent, the code should also rely on actual interfaces to make, for example, `MyObjectClass` having the `interfaceField`. As This could be done in a handful of ways, it is not responsibility of this package to define it.

**Comment by babbarankit** [comment]
https://github.com/indigotech/graphql-schema-decorator/issues/28#issuecomment-340250573
As very little I have understood from GraphQL Documentation, I think it won't be so fair to interpret Interfaces it in terms of code reusability (for code reusability Abstract seems more proper term).

Interfaces in GraphQL are more concerned towards how client will query the schema and be able to get results which have similar properties, (like Node Interface popularly used in Relay which is like the entry point of any DB-Model ).
(Typescript have different meaning of Interface to add to more complication 😀  )

**Comment by felipesabino** [comment]
> I didn't test the schema to make sure it is valid, as far as graphql docs goes there isn't a specific disclaimer regarding interfaces and input types, so I am assuming that anything goes.

Input types itself can be Interfaces but it can not be used as [input arguments are validated to be only `InputType`](https://github.com/graphql/graphql-js/blob/2419c3dc9596a031e6df87810d2f64111a4ae3f8/src/type/definition.js#L576-L578), so a validation was put in place

>  I think it won't be so fair to interpret Interfaces it in terms of code reusability (for code reusability Abstract seems more proper term).

@babbarankit  Interesting! And I noticed the same while reading and then implementing the resolver function at #46, could you also take a look?
