### ISSUE TITLE
@Root Decorator is missing in exports

### ISSUE THREAD

**Issue by babbarankit** [indigotech/graphql-schema-decorator#49]
Fix `@Root` issue regarding exporting it as a decorator

- [x] Add it to exports
- [x] Create functional tests

**Comment by felipesabino** [comment]
@babbarankit I complemented the issue to include the functional tests to this decorator. I guess if there were tests for this, the missing export issue wold have been more visible.

**Comment by babbarankit** [comment]
Thanks @felipesabino for the merge. I am not so familiar with writing tests, but will try to do it.
