### ISSUE TITLE
Create After Decorator

### ISSUE THREAD

**Issue by marcelorisse** [indigotech/graphql-schema-decorator#53]
Add middleware that is executed after function execution, similar to `Before` decorator.

**Comment by felipesabino** [comment]
This _middleware_ should:

- Expose:
  - `Context`
  - The resolved value from the resolve function it is wrapping
  - `Root` (not mandatory, but nice to have if needed changing/evaluating the resolved value based on the object that was provided to the resolver)
- Fail resolver if its callback function throws or the `next` callback is called with an error
- Should allow changing the resolver return value if next callback is called with a value
