### ISSUE TITLE
Bug: Circular field dependency results in maximum call stack

### ISSUE THREAD

**Issue by VojtaStanek** [indigotech/graphql-schema-decorator#64]
This code:
```js
import {
	Schema,
	Query,
	ObjectType,
	Field,
	schemaFactory
} from 'graphql-schema-decorator'

@ObjectType()
class QueryType {
	@Field()
	other(): QueryType {
		return null
	}
}

@Schema()
class SchemaType {
	@Query() query: QueryType
}

schemaFactory(SchemaType)
```

Results in:
```
RangeError: Maximum call stack size exceeded
```

**Comment by felipesabino** [comment]
@Cactucs Yap, circular references are still not being handled, sorry about that.

I will this open so that we can tackle after [1.0](https://github.com/indigotech/graphql-schema-decorator/milestone/1) is released.

**Comment by felipesabino** [comment]
@Cactucs Oh, meanwhile please feel free to send us a PR with a fix suggestion 😉

**Comment by pie6k** [comment]
I've created PR that solves this: https://github.com/indigotech/graphql-schema-decorator/pull/72
