### ISSUE TITLE
Is it possible to create custom scalars like DateTime?

### ISSUE THREAD

**Issue by pie6k** [indigotech/graphql-schema-decorator#74]
I've got some field that in typescript has `Date` type. I'd like to have it coveret in more advanced way than string (eg, having some parsing in both directions). Is it possible?

**Comment by felipesabino** [comment]
Hi @pie6k, you should take a look at [`graphql-iso-date`](https://github.com/excitement-engineer/graphql-iso-date), which is the one I have been using in my projects whenever date parsing is needed.
